### ISSUE TITLE
Boost Application (Windows 7) started all of a sudden with "No Storage Mount" 

### ISSUE THREAD

**Issue by rahulsaini** [BoostIO/boost-releases#18]
I had created a Boost Notes data folder at : D:\BoostCoding  which has the boostnote.json and notes folder with all notes ending in .cson intact . I had created many notes with some as plain text and some as Markdown. I have lost access to notes from Boost App. See attached issue images.
![captureb1](https://cloud.githubusercontent.com/assets/1378753/26548354/673a0752-4491-11e7-9d46-ffa64f65528a.JPG)
![captureb2](https://cloud.githubusercontent.com/assets/1378753/26548358/6cc0ffe6-4491-11e7-8d5e-ac7e636c3b08.JPG)

**Comment by asmsuechan** [comment]
Hi, @rahulsaini! Sorry for late.

This repository is only for releasing. So please re-create issue on https://github.com/BoostIO/Boostnote/issues/new.

Thank you!
