### ISSUE TITLE
Feature Request: Add Inline Images

### ISSUE THREAD

**Issue by felipemeamaral** [BoostIO/boost-releases#2]
I really love Boostnote, it's a indispensable tool on my workflow.
But, there's something that I really miss: **inline images support** (from PC and clipboard content)
Used to use _Quiver_ (Boostnote alternative for macOS) and it was one of the most **killer** features.
Hope you read it and fill my request.
Thank you for develop such a incredible productivity tool.
God bless you all!
Cheers from Brazil!

**Comment by Rokt33r** [comment]
@pulgalipe Sorry for my late answer. We're currently working it now. 😄 
https://github.com/BoostIO/Boostnote/issues/80
