### ISSUE TITLE
Why is there 2 apps and 3 download locations, which one do I use?

### ISSUE THREAD

**Issue by 825i** [BoostIO/boost-releases#48]
There's 3 pages to download Boostnote. Which one is a person supposed to use, to get the latest version and why are two being worked on at the same time?

Is it this one: https://github.com/BoostIO/BoostNote.next/releases
This one: https://github.com/BoostIO/boost-releases/releases
Or this one (Download Linux App): https://boostnote.io/

Please make this a bit less confusing...

EDIT: [I guess the first one?](https://github.com/BoostIO/BoostNote.next/issues/67)

Still very confusing...

**Comment by Rokt33r** [comment]
Sorry for my late response.
The links in https://boostnote.io/ are same to the ones in https://github.com/BoostIO/BoostNote.next/releases.
And the links in this repository are for the old app. 

So if you don't need to use the old app, you can directly download the new app from https://boostnote.io. If you want to keep using the old app, you should download app from the release page of this repository.
