### ISSUE TITLE
32-bits Debian Support

### ISSUE THREAD

**Issue by haddagart** [BoostIO/boost-releases#6]
We will really appreciate it if you release **32 bits versions**. I saw the application on a friend's computer and _I love it_. Please can you release the support for 32 bits (I am currently using Windows and Linux) both with a 32 bits architecture.

**Comment by sota1235** [comment]
Thank you for creating issue.
This repository is only for releasing. So please re-create issue on [this page](https://github.com/BoostIO/Boostnote/issues).

Thank you!
